repo-info:
- name: repo-1
  url: https://github.com/yassen-appraid/repo-1.git
  branch: main
  commit-hash: feba88a398c0fa0e789c8468481fe187cdc50223
ws-status:
- name: repo-2
  url: https://github.com/yassen-appraid/repo-2.git
  branch: main
  commit-hash: 681869db5576ea99d41794010dd5a77c57d7b6b5
- name: repo-4
  url: https://github.com/yassen-appraid/repo-4.git
  branch: main
  commit-hash: 7ab7e0f4a0b79fc6dd1660cfc909898802e4c774
- name: glores
  url: https://github.com/yassen-appraid/glores.git
  branch: main
  commit-hash: 6041a12dc323a574b7e25ef383e14be04b358347
- name: repo-3
  url: https://github.com/yassen-appraid/repo-3.git
  branch: main
  commit-hash: d1fb23bfd2d8fcb5f9f82d316027237108df1ce8
- name: repo-5
  url: https://github.com/yassen-appraid/repo-5.git
  branch: main
  commit-hash: 457d6c608c6638704584a5b9f981453e89701d11
